#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Kwiki-PerlPkgFormatter
version:      0.0.3
version_from: PerlPkgFormatter.pm
installdirs:  site
requires:
    Test::More:                    
    CGI::Kwiki::Formatter:         

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_03
